version: "2"
services:
    frontend:
        container_name: frontend-container
        build: ./frontend
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - backend
        networks:
            - appnetwork
    backend:
        container_name: backend-container
        build: ./backend
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongodb
        networks:
            - appnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - appnetwork
networks:
    appnetwork:
        driver: bridge